server:
  port: 9090

spring:
  datasource:
    username: root
    password: "123456"
    url: jdbc:mysql://localhost:3306/bms_app?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver

# 整合mybatis
#mybatis:
#  mapper-locations: classpath:mybatis/mapper/*.xml

mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# it works
springdoc:
  swagger-ui: path=/swagger-ui.html